{{- /* https://github.com/mikutas/linkerd-installation */}}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  finalizers:
  - resource-finalizer.argocd.argoproj.io
  name: linkerd
  namespace: {{ .Release.Namespace }}
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - name: linkerd-control-plane
        namespace: linkerd
        path: linkerd-control-plane
      - name: linkerd-crds
        namespace: linkerd
        path: linkerd-crds
      - name: linkerd-viz
        namespace: linkerd-viz
        path: linkerd-viz
  template:
    metadata:
      name: {{ "'{{.name}}'" }}
    spec:
      project: admin
      source:
        path: {{ "'{{.path}}'" }}
        repoURL: {{ .Values.linkerd.repoURL }}
        targetRevision: {{ .Values.linkerd.targetRevision }}
      destination:
        server: https://kubernetes.default.svc
        namespace: {{ "'{{.namespace}}'" }}
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
      ignoreDifferences:
      - kind: Secret
        jsonPointers:
        - /data/tls.crt
        - /data/tls.key
      - group: admissionregistration.k8s.io
        kind: MutatingWebhookConfiguration
        jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
      - group: batch
        kind: CronJob
        jsonPointers:
        - /spec/schedule
      - group: apiregistration.k8s.io
        kind: APIService
        jsonPointers:
        - /spec/caBundle
